# Advanced Wi-Fi Track Data Clean

This method re-clean data according to track repeat frequency ( caused by unstable signal appears among multiple trackers) based on given basic cleaned data.

Generate **virtual wifi tracker** after cleaning.(Virtual wifi trackers' id will be under zero)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mat
import os
import datetime
import time
from tqdm import tqdm
import plotly.express as px

mat.rcParams['font.family'] = 'SimHei'
mat.rcParams['font.sans-serif'] = 'SimHei'

import warnings
warnings.filterwarnings('ignore')

## Read Data

In [10]:
df_read = pd.read_csv(os.getcwd()+'/cleaned_data/dacang/dacang_cleaned_data_basic.csv')
df = df_read.copy()
df_read

          a   r                    t                        m
0        22 -43  2022-07-05 23:49:36      48,74,38,155,214,98
1        22 -35  2022-07-05 23:49:36    252,107,240,89,142,53
2        22 -42  2022-07-05 23:49:36  164,125,159,153,152,106
3        22 -38  2022-07-05 23:49:47    252,107,240,89,142,53
4        22 -42  2022-07-05 23:49:47  164,125,159,153,152,106
...      ..  ..                  ...                      ...
1916096  66 -49  2022-08-07 23:44:30   88,102,186,101,140,144
1916097  66 -49  2022-08-07 23:46:54   88,102,186,101,140,144
1916098  66 -48  2022-08-07 23:48:38   88,102,186,101,140,144
1916099  66 -49  2022-08-07 23:51:14   88,102,186,101,140,144
1916100  66 -48  2022-08-07 23:54:42   88,102,186,101,140,144

[1916101 rows x 4 columns]

In [11]:
#label each mac with date
pbar = tqdm(total=len(df))
df['oriMac'] = df['m']
df.t = pd.to_datetime(df.t)
df['calender'] = df.t.apply(lambda x : str(x.month)+'.'+str(x.day))
for index,row in df.iterrows():
    df.loc[index,'m'] = str(row['calender'])+'-'+row.m
    pbar.update(1)
pbar.close()
df

100%|██████████| 1916101/1916101 [01:38<00:00, 19509.40it/s]

,a,r,t,m,oriMac,calender
0,22,-43,2022-07-05 23:49:36,"7.5-48,74,38,155,214,98","48,74,38,155,214,98",7.5
1,22,-35,2022-07-05 23:49:36,"7.5-252,107,240,89,142,53","252,107,240,89,142,53",7.5
2,22,-42,2022-07-05 23:49:36,"7.5-164,125,159,153,152,106","164,125,159,153,152,106",7.5
3,22,-38,2022-07-05 23:49:47,"7.5-252,107,240,89,142,53","252,107,240,89,142,53",7.5
4,22,-42,2022-07-05 23:49:47,"7.5-164,125,159,153,152,106","164,125,159,153,152,106",7.5
...,...,...,...,...,...,...
1916096,66,-49,2022-08-07 23:44:30,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1916097,66,-49,2022-08-07 23:46:54,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1916098,66,-48,2022-08-07 23:48:38,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1916099,66,-49,2022-08-07 23:51:14,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1916100,66,-48,2022-08-07 23:54:42,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7

In [12]:
len(df.m.unique())

31798

In [13]:
#删除打上标签后只出现过一次的mac
df = df[df.duplicated('m',keep=False)]
df

,a,r,t,m,oriMac,calender
0,22,-43,2022-07-05 23:49:36,"7.5-48,74,38,155,214,98","48,74,38,155,214,98",7.5
1,22,-35,2022-07-05 23:49:36,"7.5-252,107,240,89,142,53","252,107,240,89,142,53",7.5
2,22,-42,2022-07-05 23:49:36,"7.5-164,125,159,153,152,106","164,125,159,153,152,106",7.5
3,22,-38,2022-07-05 23:49:47,"7.5-252,107,240,89,142,53","252,107,240,89,142,53",7.5
4,22,-42,2022-07-05 23:49:47,"7.5-164,125,159,153,152,106","164,125,159,153,152,106",7.5
...,...,...,...,...,...,...
1916096,66,-49,2022-08-07 23:44:30,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1916097,66,-49,2022-08-07 23:46:54,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1916098,66,-48,2022-08-07 23:48:38,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1916099,66,-49,2022-08-07 23:51:14,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1916100,66,-48,2022-08-07 23:54:42,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7

## 保存或读取已打上date标签的dataframe

In [3]:
#df.to_csv(os.getcwd()+"/cleaned_data/dacang/temp/dacang_cleaned_data_dataLabeled.csv",index=False)
df = pd.read_csv(os.getcwd()+"/../temp/dacang_cleaned_data_dataLabeled.csv")
df

,a,r,t,m,oriMac,calender
0,22,-43,2022-07-05 23:49:36,"7.5-48,74,38,155,214,98","48,74,38,155,214,98",7.5
1,22,-35,2022-07-05 23:49:36,"7.5-252,107,240,89,142,53","252,107,240,89,142,53",7.5
2,22,-42,2022-07-05 23:49:36,"7.5-164,125,159,153,152,106","164,125,159,153,152,106",7.5
3,22,-38,2022-07-05 23:49:47,"7.5-252,107,240,89,142,53","252,107,240,89,142,53",7.5
4,22,-42,2022-07-05 23:49:47,"7.5-164,125,159,153,152,106","164,125,159,153,152,106",7.5
...,...,...,...,...,...,...
1899913,66,-49,2022-08-07 23:44:30,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1899914,66,-49,2022-08-07 23:46:54,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1899915,66,-48,2022-08-07 23:48:38,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1899916,66,-49,2022-08-07 23:51:14,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1899917,66,-48,2022-08-07 23:54:42,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7

## 以天为单位清理异常mac

In [4]:
#获取每个mac一天中经过的探针数：a_count
count_list = df.groupby('m').a.value_counts()
df_count = count_list.to_frame().reset_index()
a_count = df_count.m.value_counts()
a_count

m
7.19-64,140,31,142,167,149     16
7.24-48,231,188,153,110,173    15
7.27-64,140,31,142,167,149     14
7.14-88,198,240,41,58,135      14
7.19-88,198,240,41,58,135      14
                               ..
7.15-16,148,53,197,58,225       1
7.15-16,74,38,133,29,213        1
7.28-240,103,40,199,90,171      1
7.28-240,103,40,135,90,171      1
7.25-164,8,250,121,194,19       1
Name: count, Length: 15615, dtype: int64

In [5]:
#获取每个mac一天中的数据量:s_count
count_list = df.m.value_counts()
count_list

m
7.10-48,74,38,155,214,98        22368
7.9-48,74,38,155,214,98         14662
7.7-48,74,38,155,214,98         11741
7.8-48,74,38,155,214,98         11646
7.11-48,74,38,155,214,98        10947
                                ...
7.28-204,129,106,183,42,73          2
7.19-64,204,31,142,167,149          2
7.28-172,254,224,205,171,204        2
7.19-112,138,9,131,173,199          2
7.14-120,251,20,50,26,70            2
Name: count, Length: 15615, dtype: int64

In [6]:
#获取每个mac一天中的持续时间
df.t = pd.to_datetime(df.t)
df

,a,r,t,m,oriMac,calender
0,22,-43,2022-07-05 23:49:36,"7.5-48,74,38,155,214,98","48,74,38,155,214,98",7.5
1,22,-35,2022-07-05 23:49:36,"7.5-252,107,240,89,142,53","252,107,240,89,142,53",7.5
2,22,-42,2022-07-05 23:49:36,"7.5-164,125,159,153,152,106","164,125,159,153,152,106",7.5
3,22,-38,2022-07-05 23:49:47,"7.5-252,107,240,89,142,53","252,107,240,89,142,53",7.5
4,22,-42,2022-07-05 23:49:47,"7.5-164,125,159,153,152,106","164,125,159,153,152,106",7.5
...,...,...,...,...,...,...
1899913,66,-49,2022-08-07 23:44:30,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1899914,66,-49,2022-08-07 23:46:54,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1899915,66,-48,2022-08-07 23:48:38,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1899916,66,-49,2022-08-07 23:51:14,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7
1899917,66,-48,2022-08-07 23:54:42,"8.7-88,102,186,101,140,144","88,102,186,101,140,144",8.7

In [7]:
mac_list = df.m.unique()
len(mac_list)

15615

In [7]:
#如
def GetDuration(df_now):
    time = df_now.iloc[len(df_now)-1].t - df_now.iloc[0].t
    time = time.components.hours+(time.components.minutes/60)
    return round(time,2)

macDur_dict = {}

for mac in tqdm(mac_list):
    df_now = df[df.m == mac]
    time = GetDuration(df_now)
    macDur_dict.update({mac:time})

macDur_dict

100%|██████████| 15615/15615 [26:51<00:00,  9.69it/s]

{'7.5-48,74,38,155,214,98': 21.83,
 '7.5-252,107,240,89,142,53': 17.02,
 '7.5-164,125,159,153,152,106': 17.02,
 '7.5-112,138,9,131,175,199': 17.02,
 '7.5-208,151,254,40,222,169': 17.02,
 '7.5-20,178,229,137,47,142': 17.02,
 '7.5-4,207,140,11,128,186': 17.02,
 '7.5-28,54,187,20,163,246': 0.12,
 '7.5-132,65,103,218,221,212': 0.1,
 '7.5-48,69,150,180,24,101': 0.07,
 '7.5-156,95,90,12,124,73': 0.05,
 '7.6-28,54,187,20,163,246': 23.98,
 '7.6-252,107,240,89,142,53': 16.85,
 '7.6-48,74,38,155,214,98': 19.23,
 '7.6-20,178,229,137,47,142': 18.9,
 '7.6-4,207,140,11,128,186': 23.98,
 '7.6-208,151,254,40,222,169': 23.97,
 '7.6-112,138,9,131,175,199': 23.98,
 '7.6-108,247,132,46,111,88': 4.67,
 '7.6-132,65,103,218,221,212': 23.85,
 '7.6-36,161,96,63,189,117': 6.0,
 '7.6-48,69,150,180,24,101': 23.93,
 '7.5-48,74,38,133,29,213': 17.0,
 '7.5-8,250,121,45,167,67': 0.12,
 '7.5-32,50,51,210,96,61': 23.9,
 '7.5-64,140,31,142,167,149': 0.12,
 '7.5-164,201,57,9,43,253': 0.13,
 '7.5-8,250,121,194,19,245': 0.13,
 '7.5-204,129,42,183,42,73': 0.1,
 '7.5-212,26,63,183,185,195': 0.05,
 '7.5-208,151,254,41,36,198': 0.03,
 '7.5-128,214,5,75,8,213': 0.07,
 '7.5-240,27,108,132,118,12': 0.05,
 '7.5-28,66,125,50,93,223': 0.05,
 '7.5-184,148,54,32,44,55': 0.08,
 '7.5-140,206,78,224,75,99': 21.75,
 '7.5-88,198,240,41,58,135': 23.47,
 '7.5-124,218,195,126,234,181': 0.0,
 '7.5-64,140,31,52,191,11': 23.98,
 '7.6-48,74,38,133,29,213': 18.92,
 '7.6-64,140,31,142,167,149': 7.23,
 '7.6-8,250,121,194,19,245': 23.98,
 '7.6-32,50,51,210,96,61': 18.92,
 '7.6-208,151,254,41,36,198': 23.98,
 '7.6-204,129,42,183,42,73': 23.98,
 '7.6-8,250,121,45,167,67': 23.97,
 '7.6-212,26,63,183,185,195': 6.93,
 '7.6-88,198,240,41,58,135': 23.88,
 '7.6-240,27,108,132,118,12': 7.05,
 '7.6-140,206,78,224,75,99': 23.88,
 '7.6-164,201,57,9,43,253': 7.22,
 '7.6-184,148,54,32,44,55': 23.88,
 '7.6-104,74,174,67,128,132': 6.48,
 '7.6-128,214,5,75,8,213': 6.93,
 '7.5-220,240,144,185,104,48': 17.03,
 '7.5-88,133,233,252,89,161': 17.03,
 '7.6-36,82,106,59,81,234': 7.03,
 '7.6-220,240,144,185,104,48': 23.93,
 '7.6-240,103,40,135,90,171': 23.93,
 '7.5-184,55,101,29,72,107': 0.12,
 '7.5-164,201,57,205,13,69': 0.1,
 '7.6-164,201,57,205,13,69': 23.85,
 '7.6-184,55,101,29,72,107': 18.9,
 '7.6-156,95,90,12,124,73': 23.87,
 '7.6-64,140,31,52,191,11': 23.97,
 '7.6-36,161,96,61,220,245': 23.93,
 '7.5-64,68,253,44,108,157': 0.05,
 '7.6-64,68,253,44,108,157': 4.53,
 '7.6-28,66,125,50,93,223': 23.82,
 '7.6-164,204,185,229,56,107': 11.02,
 '7.6-236,193,171,217,136,197': 6.97,
 '7.6-108,33,162,235,7,87': 6.93,
 '7.5-28,72,206,164,132,189': 23.78,
 '7.6-28,72,206,164,132,189': 7.23,
 '7.6-220,245,5,135,188,48': 7.18,
 '7.6-156,174,211,194,70,96': 6.83,
 '7.6-220,245,5,135,187,95': 23.82,
 '7.6-64,200,31,163,246,107': 23.75,
 '7.6-192,46,37,42,205,205': 16.75,
 '7.6-124,218,195,126,234,181': 23.62,
 '7.6-8,74,207,99,147,223': 18.98,
 '7.6-28,2,25,109,232,179': 6.35,
 '7.6-140,37,5,134,24,48': 23.75,
 '7.6-72,70,193,160,220,65': 6.15,
 '7.6-172,115,82,76,172,89': 6.92,
 '7.6-72,125,46,236,65,206': 5.45,
 '7.6-48,231,188,153,110,173': 2.48,
 '7.6-228,163,47,85,234,94': 6.6,
 '7.6-252,171,144,115,155,102': 5.5,
 '7.6-164,125,159,153,152,106': 23.0,
 '7.6-32,238,40,60,214,136': 4.73,
 '7.6-24,2,174,207,62,51': 5.87,
 '7.6-36,161,96,62,63,219': 23.2,
 '7.6-188,206,37,205,243,112': 5.6,
 '7.6-48,74,38,155,86,98': 0.68,
 '7.6-212,131,4,236,83,154': 5.53,
 '7.6-92,74,31,185,183,247': 4.0,
 '7.6-48,74,38,155,214,96': 4.32,
 '7.6-156,95,91,12,124,73': 2.12,
 '7.6-20,94,105,93,76,199': 22.45,
 '7.6-112,58,81,118,159,27': 5.45,
 '7.6-4,207,141,11,128,186': 3.53,
 '7.5-88,102,186,101,140,144': 0.07,
 '7.6-88,102,186,101,140,144': 11.45,
 '7.6-236,1,238,73,129,10': 3.52,
 '7.6-204,8,251,70,125,190': 5.12,
 '7.6-244,96,226,16,224,222': 4.58,
 '7.6-72,149,7,30,171,33': 5.13,
 '7.6-72,125,46,223,247,70': 1.92,
 '7.6-164,125,159,153,164,102': 4.58,
 '7.6-48,74,39,155,214,98': 0.25,
 '7.6-156,40,64,137,101,160': 0.0,
 '7.6-36,82,106,59,81,232': 0.2,
 '7.6-176,223,193,193,47,17': 2.05,
 '7.6-176,241,236,211,105,14': 2.45,
 '7.6-48,74,38,155,215,98': 0.25,
 '7.6-88,133,233,252,89,161': 18.33,
 '7.6-116,21,117,93,235,62': 18.12,
 '7.6-124,161,119,225,7,54': 0.68,
 '7.6-152,59,103,48,125,41': 0.33,
 '7.6-108,217,76,95,253,145': 23.98,
 '7.6-24,208,197,242,97,13': 1.28,
 '7.6-248,45,124,72,127,16': 1.05,
 '7.6-36,161,96,62,65,247': 0.87,
 '7.6-204,102,10,209,112,18': 0.87,
 '7.6-36,17,69,161,50,93': 17.8,
 '7.6-92,102,108,72,204,105': 0.25,
 '7.5-172,48,74,38,155,214': 0.0,
 '7.5-164,48,74,38,133,29': 0.0,
 '7.6-4,212,66,137,157,91': 0.0,
 '7.6-8,250,121,183,224,101': 0.12,
 '7.6-152,59,103,48,125,65': 0.0,
 '7.6-156,116,3,24,100,145': 0.12,
 '7.6-208,151,254,41,36,162': 0.57,
 '7.6-136,191,228,175,202,9': 23.98,
 '7.6-56,138,190,37,3,117': 0.0,
 '7.6-28,209,7,152,33,91': 0.18,
 '7.6-76,24,154,44,218,251': 0.33,
 '7.6-60,134,209,115,214,231': 0.25,
 '7.6-172,93,92,15,82,225': 0.0,
 '7.6-112,71,233,44,21,7': 16.75,
 '7.7-164,201,57,205,13,69': 6.87,
 '7.7-32,50,51,210,96,61': 14.72,
 '7.7-48,74,38,155,214,98': 15.85,
 '7.7-20,178,229,137,47,142': 23.98,
 '7.7-184,148,54,32,44,55': 7.43,
 '7.7-184,55,101,29,72,107': 23.98,
 '7.6-212,109,109,134,11,60': 0.2,
 '7.7-212,109,109,134,11,60': 0.13,
 '7.7-28,54,187,20,163,246': 8.05,
 '7.7-252,107,240,89,142,53': 15.85,
 '7.7-4,207,140,11,128,186': 23.98,
 '7.7-208,151,254,40,222,169': 8.05,
 '7.7-20,94,105,93,76,199': 5.4,
 '7.7-8,250,121,45,167,67': 8.33,
 '7.7-48,74,38,133,29,213': 23.98,
 '7.7-36,17,69,161,50,93': 7.35,
 '7.7-36,161,96,62,63,219': 4.42,
 '7.7-156,95,90,12,124,73': 8.3,
 '7.7-240,98,90,159,90,25': 23.87,
 '7.7-64,140,31,52,191,11': 23.75,
 '7.7-124,218,195,126,234,181': 23.68,
 '7.7-92,102,108,72,204,105': 23.92,
 '7.7-112,138,9,131,175,199': 23.85,
 '7.7-140,206,78,224,75,99': 1.87,
 '7.7-240,103,40,135,90,171': 23.97,
 '7.7-140,37,5,134,24,48': 17.12,
 '7.7-220,240,144,185,104,48': 17.08,
 '7.7-220,245,5,135,187,95': 8.23,
 '7.7-112,71,233,44,21,7': 23.98,
 '7.7-208,151,254,41,36,198': 23.93,
 '7.7-204,129,42,183,42,73': 14.72,
 '7.7-24,2,174,207,62,51': 8.05,
 '7.7-128,214,5,75,8,213': 23.93,
 '7.7-8,250,121,194,19,245': 8.1,
 '7.7-28,66,125,50,93,223': 23.85,
 '7.7-240,27,108,132,118,12': 23.8,
 '7.7-8,250,121,183,224,101': 23.85,
 '7.7-88,198,240,41,58,135': 23.83,
 '7.7-164,201,57,9,43,253': 23.77,
 '7.7-48,69,150,180,24,101': 23.98,
 '7.7-108,33,162,235,7,87': 8.18,
 '7.7-64,68,253,44,108,157': 20.95,
 '7.7-88,133,233,252,89,161': 8.3,
 '7.7-36,82,106,59,81,234': 17.12,
 '7.7-88,214,151,17,133,245': 23.43,
 '7.7-244,96,226,16,224,222': 7.7,
 '7.7-164,204,185,229,56,107': 23.67,
 '7.7-88,102,186,101,140,144': 14.32,
 '7.7-48,74,38,27,214,98': 7.5,
 '7.7-192,46,37,42,205,205': 8.18,
 '7.7-36,161,96,61,220,245': 7.92,
 '7.7-48,231,188,153,110,173': 23.7,
 '7.7-104,74,174,67,128,132': 23.55,
 '7.7-28,2,25,109,232,179': 7.67,
 '7.7-64,140,31,142,167,149': 23.43,
 '7.7-108,217,76,95,253,145': 23.0,
 '7.7-164,125,159,153,164,102': 7.8,
 '7.7-132,65,103,218,221,212': 23.27,
 '7.7-164,125,159,153,152,106': 15.27,
 '7.7-152,207,83,224,116,138': 20.55,
 '7.7-24,208,197,242,97,13': 6.55,
 '7.7-8,74,207,99,147,223': 7.33,
 '7.7-36,161,96,63,189,117': 4.3,
 '7.7-112,58,81,118,159,27': 22.75,
 '7.7-164,125,159,153,152,107': 3.42,
 '7.7-164,125,159,153,152,74': 3.42,
 '7.7-36,201,57,205,13,69': 1.3,
 '7.7-184,148,54,48,44,55': 1.08,
 '7.7-156,227,63,154,26,70': 2.1,
 '7.7-156,116,3,24,100,145': 6.88,
 '7.7-208,151,254,41,36,162': 6.67,
 '7.7-72,125,46,223,247,70': 2.1,
 '7.7-92,74,31,185,183,247': 6.0,
 '7.7-72,149,7,30,171,33': 5.63,
 '7.7-64,200,31,163,246,107': 6.13,
 '7.7-228,163,47,85,234,94': 21.25,
 '7.7-48,66,38,155,214,98': 3.9,
 '7.7-236,1,238,73,129,10': 21.13,
 '7.7-48,74,36,155,214,98': 2.6,
 '7.7-168,48,74,38,155,214': 4.57,
 '7.7-212,131,4,236,83,154': 2.12,
 '7.7-212,26,63,183,185,195': 4.68,
 '7.7-108,247,132,46,111,88': 4.12,
 '7.7-156,40,64,137,101,160': 4.48,
 '7.7-48,74,6,155,214,98': 1.4,
 '7.7-156,245,49,209,69,163': 4.53,
 '7.7-48,74,38,155,214,96': 3.28,
 '7.7-124,161,119,225,7,54': 0.25,
 '7.7-236,193,171,217,136,197': 19.25,
 '7.7-176,223,193,193,47,17': 23.97,
 '7.7-72,125,46,236,65,206': 1.28,
 '7.7-168,226,195,232,204,104': 0.0,
 '7.7-168,226,195,233,6,76': 23.98,
 '7.7-48,74,38,219,214,98': 1.67,
 '7.7-156,174,211,194,70,96': 2.83,
 '7.7-48,74,39,155,214,98': 17.77,
 '7.7-32,50,55,210,96,61': 0.77,
 '7.7-172,93,92,15,82,225': 18.05,
 '7.7-76,24,154,44,218,251': 1.32,
 '7.7-64,140,31,52,183,11': 0.47,
 '7.7-152,59,103,48,125,41': 1.28,
 '7.7-216,50,20,254,96,65': 1.58,
 '7.7-116,21,117,93,235,62': 1.98,
 '7.7-248,45,124,72,127,16': 1.8,
 '7.7-208,90,253,157,51,31': 1.73,
 '7.7-4,212,66,137,157,91': 0.17,
 '7.7-112,74,38,155,214,98': 0.5,
 '7.7-28,209,7,152,33,91': 17.07,
 '7.7-72,90,63,36,160,218': 0.0,
 '7.7-8,74,207,67,147,223': 1.03,
 '7.7-72,76,134,151,123,179': 0.23,
 '7.7-104,48,161,48,74,38': 0.0,
 '7.7-240,144,185,104,48,183': 16.9,
 '7.7-224,185,77,225,63,182': 0.0,
 '7.7-92,255,255,144,7,131': 0.18,
 '7.7-164,4,80,242,145,20': 0.02,
 '7.7-196,152,92,41,196,143': 0.23,
 '7.7-208,64,239,26,134,191': 0.0,
 '7.7-220,245,5,135,188,48': 0.33,
 '7.7-40,53,69,96,185,108': 7.83,
 '7.7-168,152,146,10,133,107': 0.13,
 '7.8-48,74,38,155,214,98': 22.68,
 '7.8-168,152,146,10,133,107': 8.98,
 '7.7-136,191,228,175,202,9': 0.05,
 '7.8-136,191,228,175,202,9': 8.07,
 '7.8-64,140,31,52,191,11': 23.92,
 '7.8-64,140,31,142,167,149': 9.73,
 '7.8-20,178,229,137,47,142': 20.75,
 '7.8-236,193,171,217,136,197': 20.72,
 '7.8-64,68,253,44,108,157': 22.63,
 '7.8-220,240,144,185,104,48': 22.67,
 '7.8-36,82,106,59,81,234': 22.65,
 '7.8-88,214,151,17,133,245': 22.6,
 '7.8-236,1,238,73,129,10': 23.17,
 '7.8-88,102,186,101,140,144': 17.0,
 '7.7-172,115,82,76,172,89': 0.08,
 '7.8-48,74,38,133,29,213': 17.13,
 '7.8-208,151,254,41,36,198': 17.13,
 '7.8-32,50,51,210,96,61': 23.65,
 '7.8-172,115,82,76,172,89': 23.65,
 '7.8-112,71,233,44,21,7': 17.13,
 '7.8-92,102,108,72,204,105': 23.97,
 '7.8-204,129,42,183,42,73': 17.08,
 '7.8-240,98,90,159,90,25': 2.38,
 '7.8-8,250,121,183,224,101': 8.25,
 '7.8-88,198,240,41,58,135': 23.88,
 '7.8-184,55,101,29,72,107': 23.98,
 '7.8-176,241,236,211,105,14': 9.67,
 '7.8-4,207,140,11,128,186': 22.73,
 '7.8-252,107,240,89,142,53': 18.47,
 '7.8-112,138,9,131,175,199': 18.45,
 '7.8-48,69,150,180,24,101': 18.4,
 '7.8-48,231,188,153,110,173': 9.72,
 '7.8-172,93,92,15,82,225': 7.08,
 '7.8-220,245,5,135,187,95': 9.35,
 '7.8-156,95,90,12,124,73': 19.68,
 '7.8-220,114,155,222,161,114': 9.62,
 '7.8-240,103,40,135,90,171': 17.63,
 '7.8-208,151,254,40,222,169': 15.73,
 '7.8-132,65,103,218,221,212': 9.6,
 '7.8-8,250,121,45,167,67': 7.87,
 '7.8-104,74,174,67,128,132': 9.48,
 '7.8-208,151,254,41,36,162': 9.58,
 '7.8-124,218,195,126,234,181': 20.52,
 '7.8-240,27,108,132,118,12': 23.47,
 '7.8-28,66,125,50,93,223': 23.52,
 '7.8-88,133,233,252,89,161': 8.78,
 '7.8-76,234,174,20,76,243': 23.72,
 '7.8-164,201,57,9,43,253': 23.45,
 '7.8-128,214,5,75,8,213': 23.53,
 '7.8-8,250,121,194,19,245': 9.52,
 '7.8-164,125,159,153,152,106': 22.68,
 '7.8-108,33,162,235,7,87': 18.1,
 '7.8-248,45,124,72,127,16': 9.37,
 '7.8-152,207,83,224,116,138': 7.07,
 '7.8-24,2,174,207,62,51': 16.7,
 '7.8-184,148,54,32,44,55': 20.22,
 '7.8-8,74,207,99,147,223': 23.35,
 '7.8-48,74,38,133,29,85': 4.4,
 '7.8-20,94,105,93,76,199': 22.85,
 '7.8-24,208,197,242,97,13': 8.87,
 '7.8-248,45,125,72,127,16': 4.72,
 '7.8-164,204,185,229,56,107': 22.87,
 '7.8-28,2,25,109,232,179': 22.48,
 '7.8-156,174,211,194,70,96': 7.67,
 '7.8-16,74,38,133,29,213': 6.13,
 '7.8-168,226,195,233,6,76': 4.0,
 '7.8-220,240,144,185,96,48': 7.93,
 '7.8-92,74,31,185,183,247': 8.0,
 '7.8-48,74,38,155,86,98': 4.43,
 '7.8-180,48,74,38,155,214': 23.37,
 '7.8-220,240,144,185,104,112': 8.08,
 '7.8-100,82,106,59,81,234': 7.67,
 '7.8-112,58,81,118,159,27': 18.57,
 '7.8-176,223,193,193,47,17': 5.78,
 '7.8-48,74,39,155,214,98': 7.33,
 '7.8-4,207,141,11,128,186': 6.13,
 '7.8-64,200,31,163,246,107': 6.67,
 '7.8-108,217,76,95,253,145': 19.58,
 '7.8-164,125,159,153,164,102': 4.23,
 '7.8-48,123,172,71,127,119': 3.77,
 '7.8-156,40,64,137,101,160': 4.55,
 '7.8-204,8,251,70,125,190': 20.53,
 '7.8-216,50,20,254,96,65': 4.57,
 '7.8-20,146,229,137,47,142': 5.98,
 '7.8-48,74,6,155,214,98': 5.68,
 '7.8-220,240,144,249,104,48': 3.55,
 '7.8-228,163,47,85,234,94': 4.02,
 '7.8-156,116,3,24,100,145': 11.7,
 '7.8-20,178,245,137,47,142': 3.55,
 '7.8-12,216,108,203,4,136': 1.15,
 '7.8-164,220,240,144,185,104': 4.45,
 '7.8-44,21,225,16,68,88': 5.02,
 '7.8-140,37,5,134,24,48': 2.9,
 '7.8-252,124,2,134,99,96': 0.37,
 '7.8-32,40,62,78,233,36': 3.5,
 '7.8-32,40,62,78,237,188': 4.1,
 '7.8-168,226,195,232,204,104': 0.0,
 '7.8-36,17,69,161,50,93': 1.62,
 '7.8-140,217,214,204,25,121': 12.83,
 '7.8-48,74,38,27,214,98': 3.92,
 '7.8-72,76,134,151,123,179': 3.42,
 '7.8-28,209,7,152,33,91': 3.0,
 '7.8-212,131,4,236,83,154': 1.83,
 '7.8-12,75,84,85,61,8': 3.27,
 '7.8-24,242,44,249,231,91': 1.88,
 '7.8-116,21,117,93,235,62': 3.3,
 '7.8-152,59,103,48,125,41': 1.08,
 '7.8-164,201,57,205,13,69': 2.78,
 '7.8-184,99,146,169,68,54': 1.5,
 '7.8-48,123,172,71,127,62': 2.02,
 '7.8-172,115,82,79,166,205': 23.98,
 '7.8-60,134,209,115,214,231': 1.9,
 '7.8-160,220,240,144,185,104': 16.1,
 '7.8-208,110,152,171,43,95': 0.02,
 '7.8-48,123,172,71,127,116': 0.13,
 '7.8-164,201,57,9,107,253': 1.12,
 '7.8-48,74,38,159,214,98': 1.62,
 '7.8-108,247,132,46,111,88': 16.0,
 '7.8-76,24,154,44,218,251': 3.03,
 '7.8-212,80,63,212,233,211': 0.02,
 '7.8-48,123,172,71,160,113': 23.92,
 '7.8-48,74,102,155,214,98': 1.8,
 '7.8-48,74,38,219,214,98': 1.3,
 '7.8-244,96,226,16,224,222': 2.35,
 '7.8-136,247,191,181,5,197': 0.8,
 '7.8-220,245,5,135,188,48': 2.18,
 '7.8-240,98,90,159,90,22': 0.25,
 '7.8-48,123,172,71,160,50': 0.0,
 '7.8-32,114,13,57,246,228': 23.98,
 '7.8-20,159,182,86,222,181': 12.93,
 '7.8-72,149,7,30,171,33': 2.18,
 '7.8-212,202,110,152,68,229': 1.78,
 '7.8-108,177,88,58,181,202': 1.62,
 '7.8-164,75,213,152,247,174': 0.0,
 '7.8-48,236,165,220,64,63': 1.22,
 '7.8-92,255,255,144,7,131': 15.5,
 '7.8-32,50,51,210,112,61': 9.25,
 '7.8-40,53,69,96,185,108': 1.68,
 '7.8-48,78,38,155,214,98': 9.47,
 '7.8-156,245,49,209,69,163': 0.15,
 '7.8-156,116,3,202,211,133': 0.02,
 '7.8-48,74,54,155,214,98': 15.62,
 '7.8-152,59,103,48,125,65': 0.57,
 '7.8-20,178,101,137,47,142': 0.15,
 '7.8-68,216,120,87,119,51': 9.52,
 '7.8-48,74,38,155,214,114': 0.43,
 '7.8-220,245,5,135,188,57': 0.53,
 '7.8-124,21,95,1,139,174': 0.13,
 '7.8-60,87,79,155,146,240': 0.12,
 '7.8-120,54,204,215,101,217': 0.0,
 '7.8-164,48,74,38,155,214': 9.18,
 '7.8-116,165,20,178,229,137': 1.28,
 '7.8-164,118,229,160,225,193': 1.38,
 '7.8-32,100,203,94,219,103': 23.92,
 '7.8-48,74,38,155,214,96': 0.23,
 '7.8-160,110,168,60,136,95': 0.0,
 '7.8-8,179,175,7,212,61': 0.08,
 '7.8-8,74,207,163,234,79': 0.05,
 '7.8-88,68,152,162,248,114': 0.0,
 '7.8-148,49,203,230,172,175': 23.98,
 '7.8-172,48,74,38,155,214': 13.13,
 '7.8-240,89,142,53,178,1': 13.13,
 '7.8-48,90,38,155,214,98': 23.88,
 '7.9-112,138,9,131,175,199': 17.63,
 '7.9-252,107,240,89,142,53': 23.6,
 '7.9-108,33,162,235,7,87': 23.62,
 '7.9-48,69,150,180,24,101': 23.6,
 '7.8-108,135,25,15,123,144': 0.23,
 '7.9-156,95,90,12,124,73': 21.22,
 '7.9-108,135,25,15,123,144': 9.07,
 '7.9-64,140,31,52,191,11': 20.97,
 '7.9-48,74,38,155,214,98': 23.15,
 '7.9-20,178,229,137,47,142': 11.85,
 '7.9-4,207,140,11,128,186': 17.63,
 '7.9-248,45,124,72,127,16': 21.72,
 '7.9-208,151,254,40,222,169': 11.23,
 '7.9-32,50,51,210,96,61': 22.27,
 '7.9-48,74,38,133,29,213': 23.15,
 '7.9-112,71,233,44,21,7': 23.13,
 '7.8-56,251,20,50,26,70': 0.15,
 '7.9-56,251,20,50,26,70': 6.33,
 '7.9-92,102,108,72,204,105': 22.13,
 '7.9-236,193,171,217,136,197': 22.12,
 '7.9-220,240,144,185,104,48': 22.27,
 '7.9-164,204,185,229,56,107': 23.97,
 '7.9-76,234,174,20,76,243': 10.68,
 '7.9-64,68,253,44,108,157': 19.0,
 '7.9-36,82,106,59,81,234': 22.25,
 '7.9-128,214,5,75,8,213': 19.3,
 '7.9-188,206,37,205,244,50': 5.8,
 '7.9-8,74,207,99,147,223': 23.63,
 '7.9-172,115,82,76,172,89': 21.72,
 '7.9-8,250,121,45,167,67': 18.18,
 '7.9-60,134,209,115,214,231': 23.87,
 '7.9-164,201,57,9,43,253': 22.25,
 '7.9-208,151,254,41,36,198': 21.9,
 '7.9-48,74,6,133,29,213': 9.23,
 '7.9-88,198,240,41,58,135': 21.62,
 '7.9-8,250,121,183,224,101': 23.83,
 '7.9-124,218,195,126,234,181': 17.13,
 '7.9-28,66,125,50,93,223': 13.77,
 '7.9-140,37,5,134,24,48': 18.93,
 '7.9-164,125,159,153,152,106': 20.27,
 '7.9-220,245,5,135,187,95': 21.7,
 '7.9-252,171,144,115,155,102': 7.98,
 '7.9-184,55,101,29,72,107': 15.65,
 '7.9-88,102,186,101,140,144': 16.28,
 '7.9-80,210,245,240,233,85': 10.5,
 '7.9-204,129,42,183,42,73': 23.33,
 '7.9-240,27,108,132,118,12': 23.58,
 '7.9-64,140,31,142,167,149': 15.17,
 '7.9-48,231,188,153,110,173': 9.7,
 '7.9-24,2,174,207,62,51': 18.68,
 '7.9-28,2,25,109,232,179': 21.48,
 '7.9-32,238,40,60,214,136': 10.05,
 '7.9-48,74,38,155,86,98': 10.02,
 '7.9-104,74,174,67,128,132': 16.37,
 '7.9-140,37,5,198,24,48': 4.1,
 '7.9-240,103,40,135,90,171': 17.38,
 '7.9-64,200,31,163,246,107': 10.05,
 '7.9-184,148,54,32,44,55': 15.32,
 '7.9-24,208,197,242,97,13': 9.63,
 '7.9-92,74,31,185,183,247': 8.0,
 '7.9-48,74,38,155,214,66': 9.28,
 '7.9-168,226,195,233,6,76': 8.0,
 '7.9-20,94,105,93,76,199': 18.45,
 '7.9-220,240,144,249,104,48': 7.17,
 '7.9-48,74,102,155,214,98': 9.5,
 '7.9-228,163,47,85,234,94': 7.1,
 '7.9-204,8,251,70,125,190': 6.27,
 '7.9-108,247,132,46,111,88': 4.32,
 '7.9-112,58,81,118,159,27': 20.15,
 '7.9-72,125,46,223,247,70': 2.8,
 '7.9-48,74,38,155,214,96': 3.68,
 '7.9-116,21,117,93,235,62': 18.32,
 '7.9-152,207,83,224,116,138': 7.82,
 '7.9-236,1,238,73,129,10': 4.83,
 '7.9-108,217,76,95,253,145': 15.38,
 '7.9-48,75,38,155,214,98': 7.97,
 '7.9-216,50,20,254,96,65': 7.05,
 '7.9-212,131,4,236,83,154': 5.03,
 '7.9-36,82,106,59,81,232': 5.62,
 '7.9-220,240,144,185,104,112': 7.28,
 '7.9-8,250,121,194,19,245': 18.48,
 '7.9-152,151,204,174,182,173': 5.12,
 '7.9-48,90,38,155,214,98': 6.9,
 '7.9-36,17,69,161,50,93': 16.45,
 '7.9-48,74,38,155,215,98': 4.82,
 '7.9-48,74,6,155,214,98': 5.67,
 '7.9-164,125,159,153,164,102': 5.5,
 '7.9-156,116,3,24,100,145': 5.07,
 '7.9-72,76,134,151,123,179': 5.53,
 '7.9-32,50,51,210,64,61': 0.8,
 '7.9-176,223,193,193,47,17': 2.22,
 '7.9-48,74,38,133,29,85': 4.17,
 '7.9-224,39,108,16,137,97': 11.3,
 '7.9-208,151,254,41,36,162': 16.15,
 '7.9-156,174,211,194,70,96': 15.52,
 '7.9-64,156,31,142,167,149': 0.5,
 '7.9-208,151,254,12,69,58': 0.02,
 '7.9-116,195,48,25,244,36': 3.08,
 '7.9-132,65,103,218,221,212': 17.2,
 '7.9-12,75,84,85,61,8': 23.95,
 '7.9-12,147,143,199,241,133': 4.48,
 '7.9-28,209,7,152,33,91': 13.32,
 '7.9-48,66,38,155,214,98': 3.83,
 '7.9-48,74,38,153,214,98': 3.68,
 '7.9-212,26,63,183,185,195': 14.5,
 '7.9-176,241,236,211,105,14': 16.25,
 '7.9-20,178,229,137,45,142': 2.0,
 '7.9-76,24,154,44,218,251': 3.33,
 '7.9-88,214,151,17,133,245': 14.57,
 '7.9-20,178,197,137,47,142': 4.12,
 '7.9-52,252,161,107,189,127': 0.0,
 '7.9-108,177,88,58,181,202': 1.5,
 '7.9-192,46,37,42,205,205': 16.22,
 '7.9-212,240,144,185,104,48': 3.12,
 '7.9-72,125,46,236,65,206': 0.5,
 '7.9-16,74,38,133,29,213': 3.3,
 '7.9-92,255,255,144,7,131': 13.28,
 '7.9-52,74,38,155,214,98': 16.4,
 '7.9-68,216,120,87,119,51': 8.17,
 '7.9-244,96,226,16,224,222': 14.67,
 '7.9-48,74,38,155,214,99': 2.32,
 '7.9-160,48,74,38,133,29': 11.67,
 '7.9-20,176,229,137,47,142': 2.0,
 '7.9-220,245,5,135,188,48': 13.73,
 '7.9-128,138,139,124,94,97': 9.6,
 '7.9-208,151,254,41,37,198': 3.12,
 '7.9-88,102,184,101,140,144': 3.07,
 '7.9-112,74,38,155,214,98': 2.87,
 '7.9-48,123,172,71,160,50': 23.93,
 '7.9-240,98,90,159,90,22': 15.22,
 '7.9-112,71,233,44,21,23': 2.28,
 '7.9-48,74,38,155,214,114': 2.28,
 '7.9-140,170,206,248,25,155': 0.07,
 '7.9-72,149,7,30,171,33': 1.83,
 '7.9-48,123,172,71,160,113': 2.33,
 '7.9-148,54,32,44,55,169': 23.75,
 '7.9-168,48,74,38,155,214': 1.02,
 '7.9-164,48,74,38,155,214': 11.92,
 '7.9-164,20,178,229,137,47': 5.17,
 '7.9-48,123,172,71,127,116': 1.68,

In [2]:
#保存或读取macDur_dict
#保存
#dict_str = str(macDur_dict)
#with open('../share/dict_file.txt', 'w') as file:
#    file.write(dict_str)

#读取
with open('../share/dict_file.txt', 'r') as file:
    dict_str = file.read()
    macDur_dict = eval(dict_str)
mac_list = list(macDur_dict.keys())
mac_dur_list = list(macDur_dict.values())

In [24]:
df_sta = pd.DataFrame({'M':[],'Dur':[],'A_count':[],'Count':[]})
df_sta

Empty DataFrame
Columns: [M, Dur, A_count, Count]
Index: []

In [25]:
#生成统计数值的dataframe
for i in range(len(mac_list)):
    df_sta.append({'M':mac_list[i],'Dur':mac_dur_list[i],'A_count':a_count[mac_list[i]],'Count':count_list[mac_list[i]]})
df_sta

AttributeError: 'DataFrame' object has no attribute 'append'

In [30]:
#获得忽略数据次数的mac-a列表
count_list = df.groupby(['m']).a.value_counts()
df_count = count_list.to_frame().reset_index()
#获得一天内出现在超过4个位置的mac
counts = df_count.m.value_counts()
mac_list = counts[counts >= 4].index
#筛选出满足条件的mac对应的数据
df = df[df.m.isin(mac_list)]
df

,a,r,t,m,oriMac,calender
0,22,-43,2022-07-05 23:49:36,"7.5-48,74,38,155,214,98","48,74,38,155,214,98",7.5
6,22,-43,2022-07-05 23:49:47,"7.5-48,74,38,155,214,98","48,74,38,155,214,98",7.5
8,22,-43,2022-07-05 23:50:00,"7.5-48,74,38,155,214,98","48,74,38,155,214,98",7.5
10,22,-35,2022-07-05 23:50:00,"7.5-20,178,229,137,47,142","20,178,229,137,47,142",7.5
12,22,-42,2022-07-05 23:50:13,"7.5-48,74,38,155,214,98","48,74,38,155,214,98",7.5
...,...,...,...,...,...,...
1916076,32,-34,2022-08-07 23:51:18,"8.7-156,95,90,12,124,73","156,95,90,12,124,73",8.7
1916081,32,-42,2022-08-07 23:51:44,"8.7-124,161,119,201,50,40","124,161,119,201,50,40",8.7
1916082,32,-27,2022-08-07 23:51:57,"8.7-156,95,90,12,124,73","156,95,90,12,124,73",8.7
1916085,32,-36,2022-08-07 23:52:49,"8.7-124,161,119,201,50,40","124,161,119,201,50,40",8.7
1916086,32,-32,2022-08-07 23:52:49,"8.7-156,95,90,12,124,73","156,95,90,12,124,73",8.7

In [50]:
count_list = df.m.value_counts()
fig = px.bar(count_list)
fig.show()